### PR TITLE
Allow --force option

### PR DESCRIPTION
**Pull request by rik**

### CODE REVIEW

**Comment by franky47** [comment]
Done, though I should probably add a condition not to run deployment on PRs (or actually fix it to deploy to specific Docker tags).

**Review by franky47 — CHANGES_REQUESTED** [review]
Could you update the documentation for this feature please? Then I can merge the PR.

**Comment by rik** [comment]
I've taken a first stab at the documentation. I've also given you the option to edit my branch ("Allow edits by maintainers")

**Review by franky47 — APPROVED** [review]
LGTM!

**Comment by franky47** [comment]
Thanks for this feature, much appreciated!

**Pull request merged**
